# Generated by Django 4.1.3 on 2024-04-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ironmongery', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('fk_ironmongery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironmongery.ironmongery')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuotationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.IntegerField(verbose_name='Cantidad de productos')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Unitario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
                ('fk_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
            ],
            options={
                'verbose_name': 'Detalle de cotización',
                'verbose_name_plural': 'Detalles de cotización',
                'ordering': ['-created'],
            },
        ),
    ]
