# Generated by Django 4.1.3 on 2024-04-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IronmongeryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='Ciudad')),
                ('cologne', models.CharField(max_length=64, verbose_name='Colonia')),
                ('street', models.CharField(max_length=64, verbose_name='Calle')),
                ('postal_code', models.CharField(max_length=64, verbose_name='Código postal')),
                ('outdoor_number', models.CharField(max_length=64, verbose_name='Número exterior')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
            ],
            options={
                'verbose_name': 'Localización de la ferreteria',
                'verbose_name_plural': 'Localización de las ferreteria',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Ironmongery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='IronmongeryLogo', verbose_name='Logo')),
                ('phone', models.CharField(max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironmongery.ironmongerylocation')),
            ],
            options={
                'verbose_name': 'Ferreteria',
                'verbose_name_plural': 'Ferreteria',
                'ordering': ['-created'],
            },
        ),
    ]
