# Generated by Django 4.1.3 on 2024-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironmongery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironmongery',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='IronmongeryBanner', verbose_name='Banner'),
        ),
    ]
