# Generated by Django 4.1.3 on 2024-10-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironmongery', '0002_ironmongery_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironmongery',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
