# Generated by Django 4.1.3 on 2025-05-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironmongery', '0003_ironmongery_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironmongerylocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='ironmongerylocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
