# Generated by Django 4.1.3 on 2024-04-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ironmongery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('fk_ironmongery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironmongery.ironmongery')),
            ],
            options={
                'verbose_name': 'Marca del producto',
                'verbose_name_plural': 'Marca de los productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Categoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
            ],
            options={
                'verbose_name': 'Categoria del producto',
                'verbose_name_plural': 'Categoria los productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('fk_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productcategory')),
            ],
            options={
                'verbose_name': 'Sub categoria del producto',
                'verbose_name_plural': 'Sub categoria los productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Imagen')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('status', models.CharField(choices=[('0', 'Alta'), ('1', 'Baja')], default=0, max_length=1, verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('upgrade', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productcategory')),
                ('fk_ironmongery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironmongery.ironmongery')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productsubcategory')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created'],
            },
        ),
    ]
